### ISSUE TITLE
Ну ты и странный

### ISSUE THREAD

**Issue by n08i40k** [Bafosteel/FridaySborBot#1]
Палить логин, пароль и токен от страницы эт странно. Замени строки на другие штуки

**Comment by Bafosteel** [comment]
О, спасибо. Думал убрал

**Comment by n08i40k** [comment]
Не зачто. Я напугал тебя когда тебе пришло сообщение с капчей?

**Comment by Bafosteel** [comment]
Слегка) Подумал, что ломанули почту сначала
